# Site settings
title: "JUDO CLI"
description: "Command-line tool for managing the lifecycle of JUDO applications"
baseurl: ""
url: "https://judo.technology"

# Repository information
repository: "BlackBeltTechnology/judo-cli"
github_username: BlackBeltTechnology

# Theme configuration (using local assets)
# remote_theme: BlackBeltTechnology/jekyll-theme-judo@develop

# Jekyll configuration
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-remote-theme

# Collections
collections:
  docs:
    output: true
    permalink: /:name/

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Commands"
    url: "/commands/"
  - title: "Configuration"
    url: "/configuration/"
  - title: "API"
    url: "/api/"
  - title: "Examples"
    url: "/examples/"
  - title: "Session"
    url: "/session/"

# Site metadata
author:
  name: "BlackBelt Technology"
  email: "info@blackbelt.hu"
  url: "https://blackbelt.hu"

# Social links
social:
  github: "BlackBeltTechnology"
  twitter: "blackbelttech"

# SEO
logo: "/assets/img/logo.svg"
twitter:
  username: blackbelttech
  card: summary

# Build settings
sass:
  sass_dir: _sass
  load_paths:
    - _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md
  - LICENSE
  - CHANGELOG.md
  - scripts/
  - internal/
  - cmd/
  - "*.go"
  - "*.sh"
  - go.mod
  - go.sum
  - .goreleaser.yml
  - VERSION
  - .github/
  - dist/

# Include
include:
  - _pages