
name: Build Test (Linux)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build judo-cli for Linux
      run: go build -o judo-linux ./cmd/judo

    - name: Verify build artifact
      run: |
        ls -lh judo-linux
        file judo-linux
